services:
  - type: web
    name: sub-cleaner-app
    env: python
    # buildCommandとstartCommandの間にこれを追加
    rootDir: . 
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: REDIRECT_URI
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
